ekf_filter_node:
  ros__parameters:
    frequency: 20.0
    sensor_timeout: 0.2
    two_d_mode: true

    publish_tf: true
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # Local odom (pose only)
    pose0: /robot/pose_cov
    pose0_queue_size: 10
    pose0_differential: false
    pose0_relative: false
    pose0_config: [
      true,  true,  false,
      false, false, true,
      false, false, false,
      false, false, false,
      false, false, false
    ]

    # GPS (x,y only)
    pose1: /gps/enu
    pose1_queue_size: 5
    pose1_differential: false
    pose1_relative: false
    pose1_config: [
      true,  true,  false,
      false, false, false,
      false, false, false,
      false, false, false,
      false, false, false
    ]
